name: test

on:
  push:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        script:
          - install-cygwin-sigbak.ps1
          - install-cygwin-sigtop.ps1

    runs-on: windows-latest

    steps:
      - name: download
        run: |
          Invoke-WebRequest -OutFile ${{matrix.script}} `
            https://github.com/tbvdm/cygwin-install-scripts/raw/master/${{matrix.script}}

      - name: run
        run: |
          '' | .\${{matrix.script}}
